/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ont777767ltd.twod;

import ont777767ltd.twod.ui.MyMouseListener;

import javax.swing.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        int w = 640;
        int h = 480;
        JFrame f = new JFrame();
        DrawingCanvas dc = new DrawingCanvas(w,h);
        f.setSize(w,h);
        f.setTitle("Drawing in Java");
        f.add(dc);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        MyMouseListener mml = new MyMouseListener();
        f.addMouseListener(mml);
        f.setVisible(true);

    }
}
